### ISSUE TITLE
Improper Git tag format results in incorrect Go module definition

### ISSUE THREAD

**Issue by cixtor** [solarkennedy/uq#10]
Hello @solarkennedy.

I noticed that you converted the project into a Go module with [commit 72729d8](https://github.com/solarkennedy/uq/commit/72729d87d7d25f2f50dad3c6f98920c8101d56a8). Thank you for that.

Unfortunately, release `0.0.4` and `0.0.5` have an incorrect Git tag format. Go modules must be prefixed with the letter `v` (short for version). Otherwise, developers are forced to reference your project in go.mod as an indirect dependency, using a Git commit hash.

If you release a new version, please consider using Git tag `v0.0.6` (notice the prefix).

Thanks in advance.

**Comment by solarkennedy** [comment]
TIL, thanks!
