### ISSUE TITLE
--version broken in 0.0.3

### ISSUE THREAD

**Issue by nhandler** [solarkennedy/uq#8]
The release of 0.0.3 broke `--version`. It now results in:

> $ uq --version
> Usage:
>   uq [-v] [-s FORMAT] [-t FORMAT] [FILE]

The expected behavior is for it to show the version number.

**Comment by solarkennedy** [comment]
That is strange. It works for me?
```
./uq --version
0.0.3
```

**Comment by nhandler** [comment]
Ah, you are correct. This was an issue on my end where I didn't update a local build recipe to take your `Makefile` changes to the `go build` invocation into account.
